spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentaltest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    upload:
      path: C:\\Users\\15637\\Desktop\\MentalTest\\static
    servlet:
      multipart:
        enabled: true # 开启文件上传
        max-file-size: 100MB
        max-request-size: 215MB # 最大请求值大小
  profiles:
#    切换工作环境
    active: dev
#    默认环境
server:
  port: 8888

